#!/bin/bash

cd ~/Projects/leginfo

if [ "$1" != "--no-download" ]; then
    echo ""
    echo "downloading..."
    db=`./01_download_latest`
    echo "found db: $db"
else
    db=$2
    echo "setting db: $db"
fi

echo "unzipping..."

./02_unzip_data $db

echo "importing..."

./03_import_data $db

