#!/bin/bash

# The output of this script is the name of the database downloaded.

# This will download the latest daily database file. When the "pubinfo_2021.zip" file, the one
# containing the law data, is updated but the daily was updated after, it downloads the one
# containing the law data and not the daily. This relies on the fact that the SoS updates
# the daily last.

urls="https://downloads.leginfo.legislature.ca.gov/pubinfo_daily_Mon.zip"
urls="$urls https://downloads.leginfo.legislature.ca.gov/pubinfo_daily_Tue.zip"
urls="$urls https://downloads.leginfo.legislature.ca.gov/pubinfo_daily_Wed.zip"
urls="$urls https://downloads.leginfo.legislature.ca.gov/pubinfo_daily_Thu.zip"
urls="$urls https://downloads.leginfo.legislature.ca.gov/pubinfo_daily_Fri.zip"
urls="$urls https://downloads.leginfo.legislature.ca.gov/pubinfo_daily_Sat.zip"
urls="$urls https://downloads.leginfo.legislature.ca.gov/pubinfo_daily_Sun.zip"
urls="$urls https://downloads.leginfo.legislature.ca.gov/pubinfo_2021.zip"

for url in $urls
do
    curl --silent -I $url | grep '^Last\-Modified:' | awk '{print "'$url' "$0}' >> /tmp/dates_1_$$.txt
done

col < /tmp/dates_1_$$.txt | \
   awk '{print $6,$5,$4,substr($7,1,2)""substr($7,4,2),$8,substr($3,1,3),$1}' | \
   sed 's/ Jan / 01 /' | sed 's/ Feb / 02 /' | sed 's/ Mar / 03 /' | \
   sed 's/ Apr / 04 /' | sed 's/ May / 05 /' | sed 's/ Jun / 06 /' | \
   sed 's/ Jul / 07 /' | sed 's/ Aug / 08 /' | sed 's/ Sep / 09 /' | \
   sed 's/ Oct / 10 /' | sed 's/ Nov / 09 /' | sed 's/ Dec / 12 /' | \
   sort > /tmp/dates_2_$$.txt

awk 'BEGIN{last="";secondLast=""}
     {secondLast = last; last = $0}
     END{if (secondLast ~ /pubinfo_2021.zip/) print secondLast; else print last}' /tmp/dates_2_$$.txt > /tmp/dates_3_$$.txt

# e.g. 2021 06 08 1121 GMT Tue https//downloads.leginfo.legislature.ca.gov/pubinfo_daily_Tue.zip

awk '{print "/usr/bin/curl --silent '\''"$NF"'\'' > data/pubinfo_daily_"$1"_"$2"_"$3"_"$4"_"$6".zip"}' /tmp/dates_3_$$.txt | /bin/sh

# echo out the name of the database just downloaded.
#
awk '{print "pubinfo_daily_"$1"_"$2"_"$3"_"$4"_"$6}' /tmp/dates_3_$$.txt

