#!/bin/bash -vx

cd data

if "$1" != "" ]; then

    db=$1

    if [ ! -d $db ]; then
        mkdir $db
        cd $db
        unzip ../$db.zip
        cd ..
    fi
else
    
    for zip in *.zip
    do
       echo $zip | \
           awk '{dir=substr($0,1,length($0)-4); print "if [ ! -d "dir" ]; then mkdir "dir"; cd "dir"; unzip ../"$0"; cd ..; fi"}' | /bin/sh
    done
fi

exit
