#!/bin/bash

if [ "$1" != "" ]; then
    db=$1
else
    db=`find data/* -prune -type d | tail -1 | sed 's/data\///'`
fi

echo "db is \"$db\""

if [ ! -d ./data/$db ]; then
    echo ""
    echo "Error, could not find database directory \"data/$db\". Aborting."
    echo ""
    exit 1
else
    echo ""
    echo "Found database directory \"data/$db\". All good."
    echo ""
fi

# We are importing a database. Delete it if it already exists.
#
echo "show databases;" | \
    mysql | \
    awk '{if ($0 == "'$db'") print "drop database '$db';"}' > /tmp/leginfo_drop_old_$$.sql

if [ -s /tmp/leginfo_drop_old_$$.sql ]; then
    mysql -vvv < /tmp/leginfo_drop_old_$$.sql
    echo ""
else
    echo ""
    echo "No existing database to clear."
    echo ""
fi

echo "create database $db;" | mysql -vvv

mysql $db < creates.sql

# Now I have to copy the LOB files over to tmp and set ownership.
#
if [ -d /tmp/data ]; then
    /bin/rm -rf /tmp/data
fi

mkdir /tmp/data

find ./data/$db -type f -name \*\.lob -exec chmod \+r {} \; -exec cp \-v {} /tmp/data \;

# Now on to the real importing....
#
echo "bill_add.sh"
./bill_add.sh $db
echo "bill_analysis_add.sh"
./bill_analysis_add.sh $db
echo "bill_detail_vote_add.sh"
./bill_detail_vote_add.sh $db
echo "bill_history_add.sh"
./bill_history_add.sh $db
echo "bill_motion_add.sh"
./bill_motion_add.sh $db
echo "bill_summary_vote_add.sh"
./bill_summary_vote_add.sh $db
echo "bill_version_add.sh"
./bill_version_add.sh $db
echo "bill_version_authors_add.sh"
./bill_version_authors_add.sh $db
echo "codes_add.sh"
./codes_add.sh $db
echo "committee_agenda_add.sh"
./committee_agenda_add.sh $db
echo "committee_hearing_add.sh"
./committee_hearing_add.sh $db
echo "daily_file_add.sh"
./daily_file_add.sh $db
echo "law_section_add.sh"
./law_section_add.sh $db
echo "law_toc_add.sh"
./law_toc_add.sh $db
echo "law_toc_sections_add.sh"
./law_toc_sections_add.sh $db
echo "legislator_add.sh"
./legislator_add.sh $db
echo "location_code_add.sh"
./location_code_add.sh $db
echo "veto_message_add.sh"
./veto_message_add.sh $db

if [ -f 04_import_site_specific ]; then
    ./04_import_site_specific $db
fi

exit
